
package com.in28minutes.courses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoursePort", targetNamespace = "http://in28minutes.com/courses")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoursePort {


    /**
     * 
     * @param getAllCourseDetailsRequest
     * @return
     *     returns com.in28minutes.courses.GetAllCourseDetailsResponse
     */
    @WebMethod(operationName = "GetAllCourseDetails")
    @WebResult(name = "GetAllCourseDetailsResponse", targetNamespace = "http://in28minutes.com/courses", partName = "GetAllCourseDetailsResponse")
    public GetAllCourseDetailsResponse getAllCourseDetails(
        @WebParam(name = "GetAllCourseDetailsRequest", targetNamespace = "http://in28minutes.com/courses", partName = "GetAllCourseDetailsRequest")
        GetAllCourseDetailsRequest getAllCourseDetailsRequest);

    /**
     * 
     * @param deleteCourseDetailsRequest
     * @return
     *     returns com.in28minutes.courses.DeleteCourseDetailsResponse
     */
    @WebMethod(operationName = "DeleteCourseDetails")
    @WebResult(name = "DeleteCourseDetailsResponse", targetNamespace = "http://in28minutes.com/courses", partName = "DeleteCourseDetailsResponse")
    public DeleteCourseDetailsResponse deleteCourseDetails(
        @WebParam(name = "DeleteCourseDetailsRequest", targetNamespace = "http://in28minutes.com/courses", partName = "DeleteCourseDetailsRequest")
        DeleteCourseDetailsRequest deleteCourseDetailsRequest);

    /**
     * 
     * @param getCourseDetailsRequest
     * @return
     *     returns com.in28minutes.courses.GetCourseDetailsResponse
     */
    @WebMethod(operationName = "GetCourseDetails")
    @WebResult(name = "GetCourseDetailsResponse", targetNamespace = "http://in28minutes.com/courses", partName = "GetCourseDetailsResponse")
    public GetCourseDetailsResponse getCourseDetails(
        @WebParam(name = "GetCourseDetailsRequest", targetNamespace = "http://in28minutes.com/courses", partName = "GetCourseDetailsRequest")
        GetCourseDetailsRequest getCourseDetailsRequest);

}
