//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.28 at 05:11:06 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.javatechie.com/soap/loan-eligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.javatechie.soap.loan_eligibility;
